name: GitHub Actions Demo
on: [push]
jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    name: A useless Job
    steps:
      - name: Bye World
        uses: orrgato/Github-Action-Experiments@main
        with: 
          input: true
  Use-Kubescape-action:
    runs-on: ubbuntu-latest
    name: Scan Repository with kubescape
    steps:
      - name: Scan it
        uses: orrgato/Kubescape-github-action@repo-scan
        with:
          scanRepository: "yes"
