name: GitHub Actions Demo
on: [push]
jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    name: A useless Job
    steps:
      - name: Bye World
        uses: orrgato/Github-Action-Experiments@main
        with: 
          input: true
